# docker compose file to start TheHomeBots development environment
services:
  # the workspace container which is used in VSCode
  workspace:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        WORKSPACE: "/home/ros/workspace"
    cap_add:
      - SYS_PTRACE
#    depends_on: 
#      - mimic3
    environment:
      DISPLAY: ${HOST_IP}:0.0
      WEBOTS_CONTROLLER_URL: tcp://${HOST_IP}:1234/
      # Needed for rendering of opengl
      LIBGL_ALWAYS_SOFTWARE: 1
      LIBGL_ALWAYS_INDIRECT: 0
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    user: ros
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ..:/home/ros/workspace

  # the mimic3 text2speech synthesizer
#  mimic3:
#    image: mycroftai/mimic3
#    ports:
#      - 59125:59125
#    volumes:
#      - ../.mimic3:/home/mimic3/.local/share/mycroft/mimic3
